<a href="https://colab.research.google.com/github/mandvithakurcin/machine_learning/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from pandas import DataFrame, read_csv
# General syntax to import a library but no functions: 
#import (library) as (give the library a nickname/alias)
import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas import sys 
#only needed to determine Python version number import matplotlib 
#only needed to determine Matplotlib version number

In [ ]:
import numpy as np
a=np.array([[[1,2,3,9],[3,4,5,10],[6,7,8,10]],[[1,2,3,10],[3,4,5,10],
[6,7,8,10]],[[1,2,3,10],[3,4,5,10],[6,7,8,10]]])
print(a.ndim)
print(a.shape)
print(a.size)


3
(3, 3, 4)
36


In [ ]:
import numpy as np


In [ ]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
import numpy as np
a=np.arange(24).reshape(2,3,4)
a.resize(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

Arrray creation 

In [ ]:
import numpy as np
a = np.array([[2,3,4],[4,5,6]])
print(a)
print(a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(b)
print(b.dtype)


[[2 3 4]
 [4 5 6]]
int64
[1.2 3.5 5.1]
float64


In [ ]:
#a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT
b = np.array([[1.5,2,3], [4,5,6]])
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(b)
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [ ]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )    # type of array explicitly defined
c


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
b=np.ones( (2,3,4), dtype=np.int16 )
n=np.empty((2,5))
print(n)


[[4.63785686e-310 3.60739284e-313 7.57510057e-310 4.63785686e-310
  0.00000000e+000]
 [0.00000000e+000 4.94065646e-323 0.00000000e+000 0.00000000e+000
  3.32156001e-309]]


In [ ]:
   
c=np.linspace( 0, 2, 9 )
ca=np.arange( 0, 2, 9 )
b=np.linspace( 0, 2, 5 )
ba=np.arange( 0, 2, 5 )
a=np.linspace( 0, 2, 20 )


aa=np.arange( 0, 2, 20 )



print(a ,aa ,b,ba,c,ca, sep='\n') 

[0.         0.10526316 0.21052632 0.31578947 0.42105263 0.52631579
 0.63157895 0.73684211 0.84210526 0.94736842 1.05263158 1.15789474
 1.26315789 1.36842105 1.47368421 1.57894737 1.68421053 1.78947368
 1.89473684 2.        ]
[0]
[0.  0.5 1.  1.5 2. ]
[0]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0]


In [ ]:
import numpy as np 
a = np.array([0,30,45,60,90]) 

print('Sine of different angles:' )
# Convert to radians by multiplying with pi/180 
print(np.sin(a*np.pi/180) )
print('\n' ) 

print( 'Cosine values for angles in array:' )
print(np.cos(a*np.pi/180))
print ('\n' ) 

print('Tangent values for given angles:' )
print(np.tan(a*np.pi/180))

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [ ]:
# Create an array with random values 
e = np.random.random((2, 2)) 
print ("\nA random array:\n", e) 
  
# Create a sequence of integers  
# from 0 to 30 with steps of 5 
f = np.arange(0, 30, 5) 
print ("\nA sequential array with steps of 5:\n", f) 
  
# Create a sequence of 10 values in range 0 to 5 
g = np.linspace(0, 5, 10) 
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g) 
  
# Reshaping 3X4 array to 2X2X3 array 
arr = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]]) 
  
newarr = arr.reshape(2, 2, 3) 
  
print ("\nOriginal array:\n", arr) 
print ("Reshaped array:\n", newarr) 
  
# Flatten array 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten() 
  
print ("\nOriginal array:\n", arr) 
print ("Fattened array:\n", flarr) 


A random array:
 [[0.93534581 0.47483734]
 [0.19025066 0.68518121]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [ ]:
import numpy as np 
  
a = np.array([[1, 3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10, 12]]) 
  
# horizontal splitting 
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 
  
# vertical splitting 
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [ ]:
# broadcasting Strenching array
import numpy as np 
  
a = np.array([0.0, 10.0, 20.0, 30.0])

b = np.array([0.0, 1.0, 2.0,5.0]) 

  
print(a + b)

In [ ]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, 3, 4)
print(a)
print(b)
print(a.sum(), b.min(), b.max())

In [ ]:
import numpy as np
ar=np.array[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]][[13,14,15][16,17,18]]
